if (self.CavalryLogger) { CavalryLogger.start_js(["gjP1Z"]); }

__d("PublicEventCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3817478708285472",metadata:{},name:"PublicEventCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometDiscussionCardRendererQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4661472223924618",metadata:{},name:"EventCometDiscussionCardRendererQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometPermalinkHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2208371695953500",metadata:{},name:"EventCometPermalinkHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PrivateEventCometTabQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3791481747537074",metadata:{},name:"PrivateEventCometTabQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PublicEventCometAboutRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3630085610391015",metadata:{},name:"PublicEventCometAboutRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PublicEventCometDiscussionRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4182662731749578",metadata:{},name:"PublicEventCometDiscussionRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometFeedVariables",["WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";f.getFeedVariables=a;function a(a,c,d,e){return{displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,eventID:a,feedLocation:"EVENT",feedbackSource:34,focusCommentID:(a=e)!=null?a:d,hoistedIDs:(e=c)!=null?e:[],privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"event",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}),null);
__d("buildPublicEventCometRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","EventCometPermalinkHeaderQuery$Parameters","PublicEventCometRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("PublicEventCometRoot.react").__setRef("buildPublicEventCometRoute.entrypoint"),function(a){a=a.routeProps;var c=a.arenaID,d=a.enableLiveVideoOnCover;a=a.eventID;var e=b("WebPixelRatio").get();return{eventPermalinkHeaderQueryReference:{parameters:b("EventCometPermalinkHeaderQuery$Parameters"),variables:{arenaID:c,enableLiveVideoOnCover:d,eventID:a,scale:e}},publicEventCometRootQueryReference:{parameters:b("PublicEventCometRootQuery$Parameters"),variables:{eventID:a}}}});e.exports=a}),null);
__d("PublicEventCometAboutRoot.entrypoint",["JSResource","WebPixelRatio","buildPublicEventCometRoute.entrypoint","PublicEventCometAboutRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=7771;a=b("buildPublicEventCometRoute.entrypoint")(b("JSResource")("PublicEventCometAboutRoot.react").__setRef("PublicEventCometAboutRoot.entrypoint"),function(a){a=a.routeProps;var c=a.arenaID;a=a.eventID;var d=g,e=b("WebPixelRatio").get();return{queries:{publicEventAboutRootQueryReference:{parameters:b("PublicEventCometAboutRootQuery$Parameters"),variables:{arenaID:c,eventID:a,nuxID:d,scale:e}}}}});e.exports=a}),null);
__d("PublicEventCometDiscussionRoot.entrypoint",["EventCometFeedVariables","JSResource","WebPixelRatio","buildPublicEventCometRoute.entrypoint","EventCometDiscussionCardRendererQuery$Parameters","PublicEventCometDiscussionRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildPublicEventCometRoute.entrypoint")(b("JSResource")("PublicEventCometDiscussionRoot.react").__setRef("PublicEventCometDiscussionRoot.entrypoint"),function(a){var c=a.routeParams;a=a.routeProps;var d=a.eventID;a=a.postIDs;var e=b("WebPixelRatio").get(),f=c.comment_id;c=c.reply_comment_id;return{queries:{eventDiscussionCardRendererQueryReference:{parameters:b("EventCometDiscussionCardRendererQuery$Parameters"),variables:b("EventCometFeedVariables").getFeedVariables(d,a,f,c)},publicEventDiscussionRootQueryReference:{parameters:b("PublicEventCometDiscussionRootQuery$Parameters"),variables:{eventID:d,scale:e}}}}});e.exports=a}),null);