if (self.CavalryLogger) { CavalryLogger.start_js(["7rirW"]); }

__d("CometVideoHomeCatalogRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3753072241378769",metadata:{},name:"CometVideoHomeCatalogRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeInjectedLiveVideoQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3463451843775237",metadata:{},name:"CometVideoHomeInjectedLiveVideoQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLatestRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4189385601078387",metadata:{},name:"CometVideoHomeLatestRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLiveRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4645659392176216",metadata:{},name:"CometVideoHomeLiveRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeSavedRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4654280254644703",metadata:{},name:"CometVideoHomeSavedRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeUpdatesSurfaceRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3693029194096525",metadata:{},name:"CometVideoHomeUpdatesSurfaceRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeCatalogRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeCatalogRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeCatalogRoot.react").__setRef("CometVideoHomeCatalogRoot.entrypoint"),function(a){return{queries:{catalogRootQueryReference:{parameters:b("CometVideoHomeCatalogRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("CometVideoHomeLiveEntryPointVariables",["WebPixelRatio","gkx","qex"],(function(a,b,c,d,e,f){"use strict";a={scale:b("WebPixelRatio").get()};d={feedLocation:"VIDEO_HOME_LIVE_TAB",feedbackSource:60,isComet:(c=b("gkx"))("708253"),isCommunityViewEntryPointEnabled:!!b("qex")._("1571809"),shareSheetRedesign:c("1365892"),useCommentsEntryPoint:c("1679116")};f.CometVideoHomeLiveHeroUFIEntryPointVariables=d;e=babelHelpers["extends"]({},a,{isComet:c("708253")});f.CometVideoHomeLiveHeroEntryPointVariables=e;c=b("gkx")("1604735")?2:4;f.SectionFetchCount=c;e=babelHelpers["extends"]({},a,d,{openInPageLiveTab:!!b("qex")._("1611011"),sectionFetchCount:c});f.CometVideoHomeLiveRootEntryPointVariables=e}),null);
__d("CometVideoHomeInjectedLiveVideo.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResourceForInteraction","CometVideoHomeInjectedLiveVideoQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){a=babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveHeroEntryPointVariables,b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveHeroUFIEntryPointVariables,{videoID:(a=a.routeProps.v)!=null?a:""});return{queries:{injectedLiveVideoQueryReference:{parameters:b("CometVideoHomeInjectedLiveVideoQuery$Parameters"),variables:a}}}},root:b("JSResourceForInteraction")("CometVideoHomeInjectedLiveVideo.react").__setRef("CometVideoHomeInjectedLiveVideo.entrypoint")};e.exports=a}),null);
__d("CometVideoHomeLatestRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeLatestRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLatestRoot.react").__setRef("CometVideoHomeLatestRoot.entrypoint"),function(a){return{queries:{latestRootQueryReference:{parameters:b("CometVideoHomeLatestRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("CometVideoHomeLiveRootEntrypoint.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResource","gkx","CometVideoHomeLiveRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{queries:{liveRootQueryReference:{parameters:b("CometVideoHomeLiveRootQuery$Parameters"),variables:babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveRootEntryPointVariables,{shouldStreamSections:b("gkx")("1760255"),trigger_data:{injected_video_id:a.routeProps.v}})}}}},root:b("JSResource")("CometVideoHomeLiveRoot.react").__setRef("CometVideoHomeLiveRootEntrypoint.entrypoint")};e.exports=a}),null);
__d("CometVideoHomeLiveInjectionRoot.entrypoint",["JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeInjectedLiveVideo.entrypoint","CometVideoHomeLiveRootEntrypoint.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLiveInjectionRoot.react").__setRef("CometVideoHomeLiveInjectionRoot.entrypoint"),function(a){return{entryPoints:{injectedLiveVideoNestedEntryPoint:{entryPoint:b("CometVideoHomeInjectedLiveVideo.entrypoint"),entryPointParams:a},liveRootNestedEntryPoint:{entryPoint:b("CometVideoHomeLiveRootEntrypoint.entrypoint"),entryPointParams:a}},extraProps:{externalLogID:a.routeProps.externalLogID,t:a.routeProps.t,v:a.routeProps.v}}});e.exports=a}),null);
__d("CometVideoHomeLiveRoot.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint","gkx","CometVideoHomeLiveRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResourceForInteraction")("CometVideoHomeLiveRoot.react").__setRef("CometVideoHomeLiveRoot.entrypoint"),function(a){return{queries:{liveRootQueryReference:{parameters:b("CometVideoHomeLiveRootQuery$Parameters"),variables:babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveRootEntryPointVariables,{shouldStreamSections:b("gkx")("1760255"),trigger_data:{injected_video_id:null}})}}}});e.exports=a}),null);
__d("CometVideoHomeSavedRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeSavedRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeSavedRoot.react").__setRef("CometVideoHomeSavedRoot.entrypoint"),function(a){return{queries:{savedRootQueryReference:{parameters:b("CometVideoHomeSavedRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("CometVideoHomeUpdatesSurfaceEntryPointVariables",["CometVideoHomeCommonEntryPointVariables","qex"],(function(a,b,c,d,e,f){"use strict";a=babelHelpers["extends"]({},b("CometVideoHomeCommonEntryPointVariables"),{feedHeroEnabled:!!b("qex")._("1418988")});e.exports=a}),null);
__d("CometVideoHomeUpdatesSurfaceRoot.entrypoint",["CometVideoHomeUpdatesSurfaceEntryPointVariables","JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeUpdatesSurfaceRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeUpdatesSurfaceRoot.react").__setRef("CometVideoHomeUpdatesSurfaceRoot.entrypoint"),function(a){return{queries:{updatesSurfaceRootQueryReference:{parameters:b("CometVideoHomeUpdatesSurfaceRootQuery$Parameters"),variables:b("CometVideoHomeUpdatesSurfaceEntryPointVariables")}}}});e.exports=a}),null);