if (self.CavalryLogger) { CavalryLogger.start_js(["0xsyA"]); }

__d("CometAlbumItemMetadataSection_story.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometAlbumItemMetadataSection_story",selections:[{args:null,kind:"FragmentSpread",name:"CometAlbumItemTimestampSection_story"}],type:"Story",abstractKey:null};e.exports=a}),null);
__d("CometAlbumItemOverlay_story.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometAlbumItemOverlay_story",selections:[{args:null,kind:"FragmentSpread",name:"CometFeedStoryActorPhotoSection_story"},{args:null,kind:"FragmentSpread",name:"CometAlbumItemMetadataSection_story"},{args:null,kind:"FragmentSpread",name:"CometAlbumItemTitleSection_story"}],type:"Story",abstractKey:null};e.exports=a}),null);
__d("CometAlbumItemTimestampSection_story.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometAlbumItemTimestampSection_story",selections:[{alias:null,args:null,kind:"ScalarField",name:"creation_time",storageKey:null},{alias:null,args:[{kind:"Literal",name:"site",value:"comet"}],kind:"ScalarField",name:"url",storageKey:'url(site:"comet")'}],type:"Story",abstractKey:null};e.exports=a}),null);
__d("CometAlbumItemTitleSection_story.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometAlbumItemTitleSection_story",selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"actors",plural:!0,selections:[{alias:null,args:null,kind:"ScalarField",name:"name",storageKey:null}],storageKey:null},{args:null,kind:"FragmentSpread",name:"CometFeedStoryActorLink_story"}],type:"Story",abstractKey:null};e.exports=a}),null);
__d("CrisisCometSeeMorePaginationButton.react",["fbt","CometProgressIndicator.react","React","TetraButton.react"],(function(a,b,c,d,e,f,g){"use strict";e.exports=a;var h=b("React");function a(a){var c=a.isLoadingNext;a=a.onPress;return h.jsx(b("TetraButton.react"),{"aria-label":c?g._("\u101c\u102f\u1015\u103a\u1006\u1031\u102c\u1004\u103a\u1014\u1031\u101e\u100a\u103a ..."):void 0,disabled:c,label:c?h.jsx(b("CometProgressIndicator.react"),{}):g._("\u1015\u102d\u102f\u1019\u102d\u102f\u1000\u103c\u100a\u1037\u103a\u101b\u103e\u102f\u101b\u1014\u103a"),onPress:a,type:"secondary"})}}),null);
__d("CometAlbumItemTimestampSection.react",["CometFeedStoryMetaSectionMiddot.react","CometLink.react","CometRelativeTimestamp.react","CometRelay","CometTimestamp.react","React","useServerTime","CometAlbumItemTimestampSection_story.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React"),i=1e3*60*60*24;function a(a){a=b("CometRelay").useFragment(g!==void 0?g:g=b("CometAlbumItemTimestampSection_story.graphql"),a.story);var c=a.creation_time;if(c==null)return null;a=a.url;c=h.jsx(j,{time:c});return h.jsxs(h.Fragment,{children:[h.jsx(b("CometFeedStoryMetaSectionMiddot.react"),{}),a!=null?h.jsx(b("CometLink.react"),{href:a,children:c}):c]})}function j(a){a=a.time;a=new Date(a*1e3);var c=b("useServerTime")();return c.valueOf()-a.valueOf()<i?h.jsx(b("CometRelativeTimestamp.react"),{date:a,format:"shortened"}):h.jsx(b("CometTimestamp.react"),{date:a})}}),null);
__d("CometAlbumItemMetadataSection.react",["CometAlbumItemTimestampSection.react","CometRelay","React","CometAlbumItemMetadataSection_story.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(a){a=b("CometRelay").useFragment(g!==void 0?g:g=b("CometAlbumItemMetadataSection_story.graphql"),a.story);return h.jsx(b("CometAlbumItemTimestampSection.react"),{story:a})}}),null);
__d("CometAlbumItemTitleSection.react",["CometFeedStoryActorLink.react","CometRelay","CometTrackingNodeProvider.react","React","stylex","CometAlbumItemTitleSection_story.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(a){a=b("CometRelay").useFragment(g!==void 0?g:g=b("CometAlbumItemTitleSection_story.graphql"),a.story);var c=a==null?void 0:a.actors[0];if(c==null)return null;a=h.jsx(b("CometTrackingNodeProvider.react"),{trackingNode:304,children:h.jsx(b("CometFeedStoryActorLink.react"),{color:"white",story:a,children:c.name})});return h.jsx("div",{className:"aahdfvyu",children:h.jsx(b("CometTrackingNodeProvider.react"),{trackingNode:10,children:a})})}}),null);
__d("CometAlbumItemOverlay.react",["CometAlbumItemMetadataSection.react","CometAlbumItemTitleSection.react","CometFeedStoryActorPhotoSection.react","CometRelay","React","TetraTextPairing.react","stylex","CometAlbumItemOverlay_story.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(a){a=b("CometRelay").useFragment(g!==void 0?g:g=b("CometAlbumItemOverlay_story.graphql"),a.story);return h.jsxs(h.Fragment,{children:[h.jsx("div",{className:"kr520xx4 j9ispegn pmk7jnqg n7fi1qx3 i09qtzwb rfe5e1s5"}),h.jsxs("div",{className:"dn56xbwz re5koujm l9j0dhe7 wkznzc2l sjgh65i0 btwxx1t3 j83agx80",children:[h.jsx(b("CometFeedStoryActorPhotoSection.react"),{story:a}),h.jsx("div",{className:"l9j0dhe7 cbu4d94t j83agx80 o8rfisnq",children:h.jsx(b("TetraTextPairing.react"),{headline:h.jsx(b("CometAlbumItemTitleSection.react"),{story:a}),headlineColor:"white",level:3,meta:h.jsx(b("CometAlbumItemMetadataSection.react"),{story:a}),metaColor:"white",reduceEmphasis:!0})})]})]})}}),null);